---
services:
  grafana:
    image: grafana/grafana:11.5.1
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_HIDE_VERSION: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/dashboards/home.json
      GF_LIVE_ALLOWED_ORIGINS: "https://*.preview.app.github.dev"
    volumes:
      - type: bind
        source: etc/grafana/provisioning
        target: /etc/grafana/provisioning
      - type: bind
        source: etc/grafana/dashboards
        target: /etc/dashboards
      - grafana:/var/lib/grafana
    pull_policy: missing
  broker:
    image: ghcr.io/tansu-io/tansu:latest
    environment:
      ADVERTISED_LISTENER_URL: tcp://broker:9092
      RUST_BACKTRACE: 1
      RUST_LOG: debug,tansu_sans_io=warn,tansu_model=warn,turso_core=warn
      STORAGE_ENGINE: "sqlite:///data/tansu.db?vacuum_into=/data/snapshot.db&maintenance_interval=1m"
      OTEL_METRIC_EXPORT_INTERVAL: 5000
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://prometheus:9090/api/v1/otlp/"
    command: ["broker"]
    ports:
      - 9092:9092
    volumes:
      - ./data/:/data/
  prometheus:
    image: prom/prometheus:v3.1.0
    ports:
      - 9090:9090
    command: --web.enable-otlp-receiver
    extra_hosts:
      - "host.docker.internal=host-gateway"
    configs:
      - source: prometheus_yaml
        target: /prometheus/prometheus.yml
  kafka39:
    image: apache/kafka:3.9.2
    command: /bin/sleep infinity
configs:
  prometheus_yaml:
    file: etc/prometheus.yaml
volumes:
  grafana:
    driver: local
